### ISSUE TITLE
Add support to generate and print QRCode from entered data

### ISSUE THREAD

**Issue by yanokwa** [getodk/xforms-spec#101]
We started a discussion at https://github.com/opendatakit/collect/issues/758 about being able to generate a barcode from within ODK Collect. 

> From collected information on Collect, I want to generate an id which will be printed as a barcode(QRCode) via Zebra iMZ220.

Any ideas on how best to represent this in XForms?

**Comment by MartijnR** [comment]
There has some discussion about this within Enketo as well. Our approach was to generate this after creating the submission in a custom client that is dedicated for this purpose. So that approach would make it fall outside of this spec. 

Do you see this as a form-level feature, i.e. in a client that for some forms needs to submit regular XML submissions and for other forms generate/print a QR code?

**Comment by lognaturel** [comment]
This is being done in Collect with a `print` appearance and will likely eventually be supported in web forms as well. We haven't so far been documenting appearances in this specification so I'm going to close. [Forum thread](https://forum.getodk.org/t/printing-id-cards/6904/6?u=ln)
