### ISSUE TITLE
Proposal: support for ranking items

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#104]
Users would like to be able to order a list of items to represent rankings.

One idea for doing this would be to add an `orx:rank` form control element analogous to `select` that also has `item` or `itemset` children. The instance would similarly represent responses to the `rank` question as a <strike>comma-separated</strike> space-separated list of values but these would be ordered and of the same length as the initial list of values rather than an unordered subset.

Of course, I'm open to other implementation ideas!

**Comment by chrislrobert** [comment]
You said "a comma-separated list" -- but current select_multiple responses are space-separated. I presume you'd want to keep it space-separated?

And I guess you would use a new field type rather than an appearance attribute for the existing select_multiple field type since, strictly speaking, this isn't just a different UI appearance but also a different functionality? You could see it wanting to support other appearance styles supported by select_multiple, dynamic loading, cascading-select filtering, etc., etc. -- so really it wants to be, for all practical purposes, the same as a select_multiple field except that (a) it allows the user to explicitly order responses, and (b) the resulting list is ordered rather than unordered. Do I have that all right?

If an appearance attribute wouldn't be quite kosher because it's not strictly UI-only, I get that (though of course it's never stopped us!). But then would a different attribute on the existing field type be another option? There'd be a few advantages: (1) it vaguely seems like overkill to make a whole new field type and have to add support for that everywhere in the universe, and (2) the default fall-back behavior for clients, data visualization tools, etc. that don't support the new attribute would be to show choices/responses as select_multiple (which seems like the fall-back behavior you'd want). If you go with a new field type, the fall-back behavior would maybe be a text field (or worse), which seems less ideal.

**Comment by lognaturel** [comment]
Apologies, @chrislrobert, I missed your response. Yes, I misspoke, the response would be space-separated.

I like the idea of a new form control element because for users/form designers, ranking is probably not obviously connected to selecting. Implementation-wise, of course they could share code.

Similarly, I'm not sure that multiselect would be a good fallback. The user would see a prompt that tells them to order things and then see a control that to them is not related. Maybe they'd check some things and if they checked everything, they could trick someone looking at the data into thinking that they had actually ordered them. If it falls back to a text field, at least it's unambiguous that something has gone wrong.

**Comment by MartijnR** [comment]
I like this feature (mostly because it would be a fun thing to develop ;)).  For users, I think that this feature would become particularly interesting when used in conjunction with a [randomize()](https://github.com/opendatakit/xforms-spec/issues/51) function. 

I agree that a text field fallback might be 'best' but that for implementing the feature a syntax very similar to a `<select>` seems to make most sense at first glance.

With a new form control there probably is no automatic fallback in most clients (at least Enketo would not show the question at all). So for a new form control any fallback behaviour would have to be actively created. 

We could consider an `<input>` with an `<itemset>` child (or with a new attribute on the input form control) that may offer the automatic fallback, but I don't know (very violating of XForms).

Do we need the label & value combo that the `<select>` syntax (both options) offer? My guess is yes, but if not, an attribute on an `<input>` element might be more attractive.

**Comment by lognaturel** [comment]
Agreed both on the fun to build and desirability of `randomize()` in this context!

I'm getting a bit in the implementation weeds that don't matter much here but Collect does fall back to a text field when there's a form control element it doesn't know about. Sometimes that can be useful but I do think we should really let the user know that it wasn't intended to be used that way. Similarly, unknown appearances are just silently ignored. Anyway, I'll take that up on the Collect side! I don't think this spec should specify anything regarding fallback behavior.

Would there be a way to do translations without separating labels and values? I'm not sure I understand quite what an attribute on an `input` element entails.

**Comment by MartijnR** [comment]
Without separating labels and values there wouldn't be a way to do translations. So I think the attribute-on-the-input element is out (the option was for this attribute to point to a nodeset to be ranked), and using `<itemset>` (and optionally, the regular fixed select `<item>`s) would be the way to go.

I agree the spec doesn't need to specify fallback behaviour. Would be nice if it automatically happened, but not a requirement imo.

So we have remaining options: `<orx:rank>` vs `<input>`, both with the same `<itemset>` child. I think I like `<orx:rank>` better at the moment. Odd that nobody seems to have solved this already (Orbeon e.g.).

**Comment by lognaturel** [comment]
I know, I was sure I'd find somebody doing this in XForms somewhere but I couldn't find it!

For the `input` case, what `type` would be specified on the bind? I don't like that it would feel so different both from other `input`s and from `select`s that seem more analogous.

**Comment by MartijnR** [comment]
I had to think about a response for a year. I think the type could be string for any solution (though it's similar to type="select", as that type doesn't actually exist). After a year of percolating, I also like a custom element better now, even though there isn't any automatic fallback (in Enketo). 

Something like (as in @ln's OP):

```xml
<!-- primary instance -->
<data>
     <ranking>b a</ranking>
</data>
<!-- body -->
<orx:rank ref="/data/ranking">
     <label>label</label>
     <hint/>
     <item>
           <label>A</label>
           <value>a</value>
     </item>
     <item>
           <label>B</label>
           <value>b</value>
     </item>
<orx:rank>
```

and with itemsets

```xml
<!-- primary instance -->
<data>
     <ranking>b a</ranking>
</data>
<!-- body -->
<orx:rank ref="/data/ranking">
     <label>label</label>
     <hint/>
     <itemset nodeset="instance('something')/root/item">
           <label ref="./label" />
           <value ref="./value" />
     </itemset>
<orx:rank>
```

**Comment by MartijnR** [comment]
Anybody else in agreement or wants to tweak this proposal further?

**Comment by MartijnR** [comment]
or strongly oppose it?

**Comment by lognaturel** [comment]
Oh, @opendatakit-bot! Sometimes you are useful but sometimes you are just annoying.

I see a +1 from @aurdipas. I mentioned this was planned in the last TSC meeting and all seemed either on board or not to have an opinion. I think we have given enough time for lazy consensus.

**Comment by MartijnR** [comment]
Sorry @opendatakit-bot, I'm still working on it. Something came up and is preventing me from working on it. Be a kind bot and have some patience.
