### ISSUE TITLE
Proposal: selfie appearance for images

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#112]
Over in Collect-land, we've been discussing adding an image appearance that forces the user to take a picture and defaults to using the front-facing camera if it exists -- opendatakit/collect#969

I imagine that this is only really relevant to mobile client implementations. I think it still makes sense to discuss here really quickly to see whether there's high-level feedback and to make other implementors of the spec aware of the addition. Does that sound right? Is that a good process for appearances moving forward?

**Comment by MartijnR** [comment]
Yes, I think it's good to mention this here for that reason. Another reason is to get some input on the appearance naming with the goal to try to re-use ("good") appearance names (though in this case probably not) and make sure they mean the same in different clients.

**Comment by lognaturel** [comment]
Awesome, that sounds great.

Well, I didn't even mention the proposed name in my writeup. Any comments on or alternatives to `selfie`?

**Comment by MartijnR** [comment]
That's brilliant! :) 👍

**Comment by tiritea** [comment]
Well, [since I seem to have an uncontrollable desire to comment on pretty much everything... :-)] I dont actually think the XForms document should necessarily being attempting to - or even have the need to? - go into quite so much detail as to explicitly specify which particular physical device on the endpoint should be use to capture the data. Rather, this degree of freedom should be left to the client implementation, aka widget, and be controlled by the user. The form simply wants an image/picture, and it can describe what it wants an image of in the upload label text. Whether that image happens to come from a front-facing camera, or back-facing camera, or even the user's photo album, is of no consequence to the XForm itself - it will get an image! (hopefully of what it asked for, but there's still no guarantee the user wont just send a picture of their cat...)

**Comment by tiritea** [comment]
as a point of reference, my XForms client's 'image' widget presents a popup from which the user can either take a picture or pick an existing one from an album. And if taking a picture, I can choose to use the front and rear facing camera. I really see no particular reason why my form needs to exert a greater degree of control over this...

**Comment by tiritea** [comment]
Reading thru collect#969 I can sympathize with this particular (and very specialized?) use-case, but forcing users to do something a particular way always raises a red flag when it comes to usability... If you want a current picture of the patient then the form should ask for one. Forcing the *live* acquisition via the camera (yet alone a particular camera!) - as opposed to, say, a picture taken an hour earlier (when perhaps it was more convenient, appropriate, possible, ...)  - whilst filling in a form only imposes additional restrictions on the user trying to complete your form, ostensibly because you dont believe they'll follow your explicit instructions. The underlying problem in the usecase as described appears to be that you are presenting a device+GUI (an Android phone running Collect) that is apparently beyond the limited capabilities of this particular audience. So I would be more inclined to say that you probably need to look at presenting a more suitable device and/or GUI (eg a stripped down custom Collect). Changing the XForms specification itself - by defining new appearances, etc - isnt appropriate IMO. As some point a spec has to assume its consumers are competent, can follow instructions, and we give them sufficient functionality to do so.

**Comment by lognaturel** [comment]
Really appreciate the comments, keep them coming!! It's so helpful to get some new perspectives in. 🙌

I can appreciate what you are saying about keeping a specification minimal but given that the ODK ecosystem exists specifically to support users with significant limits -- low literacy, basic phones, low power, etc -- this feels in scope for clients that can support it. That's what makes this the "ODK XForms" spec, NOT the "XForms" spec. 

In general, I think we've been fairly lax about introducing new appearances. They should be treated as hints to the client that clients can ignore with very little repercussion (just loss of convenience and control, basically). Curious to know what @MartijnR thinks about this one!

**Comment by tiritea** [comment]
Will do. Apologies if I'm being too, um, 'provocative'... ;-) I'll freely admit I'm coming from a much more purest standards background, where the emphasis is on being curt, precise, and minimal-enough-to-still-get-the-job-done. And yes, I've noticed y'all been pretty, well, shall we say, "uninhibited" when it comes to appearances... lol [FYI I'm already ignoring your gravest transgressions in my XForms client. ha!]

**Comment by lognaturel** [comment]
Hey, I told you 'provocative' is good in my book! 😄

There are definitely things that have been expressed as appearances that are not client hints. That's unfortunate and hopefully we can add alternatives and deprecate some over time.

**Comment by tiritea** [comment]
On some reflection, I guess its fair to say that within the ODK ecosystem, it is the *client* (Collect) - not the server (Aggregate) - who calls the shots. Whereas I tend to view the *server* and the data it manages as being most important. If Aggregate and, by implication, ODK Xforms spec, exists ostensibly to serve the needs of the Android ODK Collect client, then adding an appearance in the XForms doc in order to drive a specific function on this client makes some sense. Something to be wary of, is that these appearances are supposed to be mutually exclusive; that is, you dont want to be add an appearance setting (to anything for that matter!) where there is a reasonable likelihood of ever wanting to customize a difference parameter. In this example, using an appearance to pick a specific camera on the device to take the image, if there are other (more important?) customizations around image capture that you may well want to someday make. ANd being forced into having to define all permutations (of desired parameters) gets ugly quickly; eg "frontCameraAndColor", "frontCameraAndMono", "rearCameraAndColor", "readCameraAndMono", ... a bit contrived I admit, but you get my drift. So I do think there needs to be some exercise of restraint in 'using up' appearances to drive client-side control settings.

**Comment by chrislrobert** [comment]
We've tended to allow space-separated lists of appearances. So, for
example, I believe that the select_one and select_multiple widgets support
combinations of appearances. Is there anything wrong with that, in
principle? While some appearances could be mutually exclusive, many are not.

**Comment by tiritea** [comment]
..."supposed to be mutually exclusive", but dont quote me on that! :-) I'd really need to dig thru the W3C XForms spec to be sure, but my guess if that given the dearth of usage of appearances therein (other than the 3 for select) I suspect its probably not even officially spelled out anywhere. But then, since y'all writing yer own spec, who cares, eh lol. I do think an excessive number of different appearances on a control probably means there's starting to be something wrong somewhere, eg the XForm is starting to go down the path of wanting an extremely fine-grained level of control over the client UI (taken to the extreme, how an HTML doc lays out every last detail on a web page). But yours is a good point, should javarosa support multiple appearance settings? I've not seen anywhere saying it does, nor that its disallowed. But its certainly something that should be spelled out explicitly (space delimited? comma delimited? ...)

**Comment by tiritea** [comment]
FYI, [XForm1.1 spec](https://www.w3.org/TR/xforms11/#attrs-ui-common) defines `appearance` as
>appearance ("full"|"compact"|"minimal" | QNameButNotNCName)
where `QNameButNotNCName` basically a qualified name; ie *singular*.
So yeah, probably a list is strictly illegal (and the W3C police will be knocking on your door any minute). :-)

**Comment by lognaturel** [comment]
Let's move the bigger picture conversation to #124! Would be fantastic to have an "appearance policy" to guide us moving forward.

@tiritea JavaRosa doesn't support appearances because it's not a client per se. Client implementations that leverage JavaRosa can choose which (if any) appearances they want to support. There may be an exception or two to that because open source wild wild west but that's the intent.

**Comment by MartijnR** [comment]
How about another appearance for "environment"?

In (some) browsers we can have 3 different modes for an image input:

1. let the OS deal with it: this means both filepickers and camera apps will be shown as options to th user -> appearance= ""
2. capture with the user-facing camera -> appearance="selfie"
3. capture with the environment-facing camera -> appearance="environment"?

**Comment by lognaturel** [comment]
That makes sense! `environment` doesn't seem very intuitive. I see it's to match HTML but since we've already broken the ranks with `selfie`, maybe we can come up with something more colloquial like `back` or `rear`?

**Comment by MartijnR** [comment]
Any other word that's most intuitive would be fine with me. Does not have to match HTML. I find it hard to choose between `back` and `rear`. Anybody else have a preference, or suggestion?

**Comment by MartijnR** [comment]
Issue is now covered by https://github.com/opendatakit/xforms-spec/issues/134. Or not?

**Comment by MartijnR** [comment]
yes
