### ISSUE TITLE
Capturing arbitrary timestamps

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#123]
Collect had a long-standing issue of not being able to capture empty dates and times -- opendatakit/collect#81. This was recently fixed but now it has come out that users were using this to capture timestamps in their forms by making time questions required but read-only. See [this mailing list conversation](https://groups.google.com/d/msg/opendatakit/R0XBiZfR8YQ/1MpE92VzHAAJ).

Arbitrary timestamping is something a number of users would like to do. It would seem like a combination of `calculate` and `now()` would help with that but there are a number of subtleties around when `now()` gets evaluated. @yanokwa has some notes about that somewhere I think. 

I don't think these kinds of timestamps make any sense in a client like Enketo, right @MartijnR? They're also not terrifically meaningful in Collect since users can go back and forth, jump around, etc. I'd like to encourage people to use #94 but I also understand that it will be pretty heavyweight.

Are there any reasonable options for explicitly supporting lightweight timestamping? Is it something that makes sense as part of the spec?

**Comment by MartijnR** [comment]
Indeed, apart from #94 and metadata (timeStart, timeEnd) there is no mechanism to run a calculation when a particular event (focus, page flip) occurs. 

After #94, I'd be a little unenthusiastic to introduce one just for the timestamp purpose (which would be XForm Actions I think). If we have other reasons to add Actions support, _lightweight timestamps_ would probably automatically become supported (and once() could be used to avoid some of the issues).

**Comment by yanokwa** [comment]
I figured I should put my notes about now() and once() in public.

First, read https://groups.google.com/d/msg/opendatakit/QVZbSidiSkU/pJtY02kjCQAJ

Then try out [time.xlsx](https://github.com/opendatakit/xforms-spec/files/992666/time.xlsx) to verify the behavior in Collect.

now() is calculated at the start of the form and recalculated when you update and save data in the form (e.g., often on finalize).

once(now()) is evaluated with the same rules, but it is only evaluated once.

When now() is evaluated depends on its relevance. If it has no relevancies, then it's evaluated at the start of the form. If it has relevancies, then it's evaluated when it is relevant.

If you close Collect, the values of now() that are stored in memory but not persisted (e.g., a node that is not relevant) and thrown away and so the values of now() inside that node that is not relevant are re-initialized.

It's really tricky for a civilian to get this right. Can we be a little more creative here, @MartijnR and @lognaturel? Maybe now() should be evaluated when that node is "seen"...

**Comment by lognaturel** [comment]
I think this is really just a JavaRosa bug we should address in opendatakit/javarosa#199.

**Comment by lognaturel** [comment]
Weird, yes, because of the implications of the word "now", but consistent with the way all other functions are evaluated.

This "lightweight time stamping" continues to be a frequent ask. Users want to be able to use their existing analysis machinery to spot check when certain questions were answered. 

@mdudzinski came up with the idea of introducing a `last-time-edited(node)` function. It would just grab a current date/time stamp and by being dependent on a particular node it would get recomputed every time the value of that node changed. That actually does seem like meaningful information to me and it makes sense in a single-page context like in Enketo. It would be easy to use with XLSForm's `${}` syntax and form developers could group all of the timestamps they want to capture in one part of the form (rather than having to place them after the question they want to capture the edit time of). 

One caveat is that `once(last-time-edited(node))` probably wouldn't make any sense and would just capture the time the form was opened.

@MartijnR @yanokwa @alihelmi87 @grzesiek2010 would love to know your thoughts.

**Comment by mdudzinski** [comment]
@lognaturel 
I did a quick testing and if we allow `once()` to take a nodeset arg, then the following snippet
`calculate="once(now(), /data/Number)"` calculates the `now()` value only once if the referenced node has been updated. 
So technically both `last-time-edited(node)` and `first-time-edited(node)` are possible.

**Comment by MartijnR** [comment]
This is very creative! 👍 

@mdudzinski in your last example of extending `once()`, the last-time-edited functionality is not yet available, I think. (note that you could do without extending once() as well by using `if()` inside of `once()`, but it has the same problem with the last-time-edited functionality.)

A similar wild idea: How about adding a node parameter to now() instead? As in `now(/path/to/node)` and `once(now(/path/to/node))`. That would provide both functionalities perhaps. Though a limitation is that emptying values screw things up for first-time-edited because once() isn't really "once", it's "if-not-empty".

**Comment by lognaturel** [comment]
> How about adding a node parameter to now() instead? As in now(/path/to/node) and once(now(/path/to/node))

That was actually @mdudzinski's original idea! I thought a new function with the same implementation might be easier to use but either would work for me.

**Comment by mdudzinski** [comment]
@MartijnR You're right. In my last comment I assumed the `last-time-edited` function is not available yet. Not sure why though :smile:

I tested and if we had `now(/path/to/node)` (`last-time-edited`) then the `once(now(/path/to/node))` function would work as expected (`first-time-edited`).

So it's only matter of usability for the end users. What will be easier? Dedicated function or extended existing one?

**Comment by MartijnR** [comment]
Ah, I see. Yes, a new function may make more sense. Will think about pros and cons but last-time-edited seems:

1. more descriptive
2. more flexible if we want to add some special behavior

Related to the second point, what should the behavior be if:
1. a form is loaded with such a calculation (`now(//node)` or `last-time-edited(//node)`) and node is empty. What is the result of the calculation upon load?
2. the same if node has default value

**Comment by lognaturel** [comment]
I personally find the dedicated functions easier to reason about. It seems really hard to explain why `now()` does one thing but `now(//node)` another to folks who don't have a full understanding of how/when evaluation of XPath functions is done. In fact I know the rules but I still got repeatedly tripped up by the name `now`. It just really feels like it should be changing as time goes by!

I would expect that "last time edited" would be the time of form opening for both an empty node and a node with a default value . I suppose another possibility would be for it to be blank? Any other possibilities you had in mind @MartijnR?

**Comment by mdudzinski** [comment]
@MartijnR @lognaturel I double checked and unfortunately `once(now(/path/to/node))` won't work out of the box :disappointed: It's because it always run upon a form load. 
Sorry for the confusion!

Anyway, I believe it's still doable to implement the `first-time-edited` but will require more work. 

Is there any particular reason why functions that are fired when a referenced node is updated, are fired upon a form load as well?

**Comment by lognaturel** [comment]
Indeed, everything is evaluated at form load and form finalization so unfortunately it looks like these ideas may not work after all. 😖 I believe these are W3C XForms evaluation rules so straying from that would be a big deviation. Frustrating that something that is so simple to describe is so challenging to find an approach for!

**Comment by mdudzinski** [comment]
@lognaturel `last-time-edited` is still simple to implement, the problem is only with `last-time-edited`. The easiest solution I can think of is to create a set of xpath functions that don't evaluate at form load. It will be a deviation as you said but only with functions invented by ODK Javarosa.

**Comment by mdudzinski** [comment]
@lognaturel The simplest and feasible solution I can think of is to create a set of functions that don't evaluate at form load. It will be a deviation as you said but only for functions that were introduced by ODK.

Names like `first-time-edited` or `last-time-edited` are actually saying that they don't evaluate at form load or any other event and are tied to the input action...

**Comment by lognaturel** [comment]
Thank you for being more creative than me, @mdudzinski! You're right that the names of the functions imply different evaluation rules. @MartijnR how does that sound to you? It's a little unusual but I think it can be documented clearly and implemented consistently. @tiritea seems like the kind of thing you'd have opinions on.

**Comment by MartijnR** [comment]
I really don't think we should go in the direction of avoiding the evaluation of certain XPath function calls (which may be part of a large XPath expression, e.g. inside `if()`) upon certain events. That 'event' information is not available to an XPath evaluator.

One (complex) way forward would be to support XForm Actions as [used by CommCare](https://dimagi.github.io/xform-spec/#actions). We could have an xforms-ready event that populates a value e.g. for node `/data/ready`. Then we could use an if() statement to only generate a timestamp if `/data/ready` has a value (i.e. if initial load has completed).

**Comment by lognaturel** [comment]
:/ I guess it would have to be a weird non-XPath function that is only valid to set a calculate, not in any other context.

I'm not seeing how an Action with an `xforms-ready` event would help. Isn't that event just form load? Seems that would give us exactly the same behavior as we have now with just using the `now()` function. I think we would need something like the [`xforms-value-changed`](https://www.ibm.com/support/knowledgecenter/en/SSS28S_8.1.0/XFDL/i_xfdl_g_xforms_events_xforms-value-changed.html) event, no?

**Comment by mdudzinski** [comment]
@MartijnR A very good point that an xpath function can be wrapped with another one! Still doable to prevent any chain of xpath functions that contain `first-time-edited` or `last-time-edited` from being evaluated at form load but it would be really odd and confusing.

@lognaturel Introducing a new event like you suggested sounds interesting. Since `setvalue` is implemented in JavaRosa, seems like a good way to go. I'll play with this and check the potential effort.

**Comment by MartijnR** [comment]
The `xforms-ready` event would fire when 

> when the forms viewing application has finished the initial set up of all XForms constructs and is ready for user interaction.

so I think after calculations-upon-load, but definitely worth checking further if that's the right event to support for this.

(https://dimagi.github.io/xform-spec/#action-events)

**Comment by lognaturel** [comment]
Ah, I think I understand what you're suggesting. Wouldn't something similar also need to be done on `xforms-revalidate` to avoid replacing the value then?

Basically it'd be a way of making the suppression of evaluation on load and finalization explicit in the form rather than implicit in the function definitions?

**Comment by tiritea** [comment]
```
<bind jr:preload="timestamp" jr:preloadParams="start" nodeset="/data/start" type="dateTime"/>
<bind jr:preload="timestamp" jr:preloadParams="end" nodeset="/data/end" type="dateTime"/>
```

vs

`<bind calculate="concat('uuid:', uuid())" nodeset="/data/meta/instanceID" readonly="true()" type="string"/>`

vs ?

I dont particularly like the way preload has gone about it, using a handful of pre-defined functions to generate values, but entirely outside of XPath (which is ostensibly doing the same thing already). Ditto the usual UUID calculation is a bit silly since it really only needs to be done once, but short of introspecting exactly what the calculation contains there's really no way the client can know what the calculation depends on, so its arguably gotta re-evaluate it every time something changes in the form(!)

But then I dont think we necessarily need to go all the way that dimaji has gone and introduce a whole new mechanism of `<setvalue event=...>` events either (arguably, their `xforms-ready` is doing what `jr:preload` is supposed to be there for...)

What would be wrong with simply adding an additional bind attribute, say `when`, which would optionally indicate to the client _when_ the corresponding calculation should be run? For example

```
<bind calculate="now()" when="xforms-ready" nodeset="/data/starttime" readonly="true()" type="dateTime"/>
<bind calculate="concat('uuid:', uuid())" when="xforms-submit" nodeset="/data/meta/instanceID" readonly="true()" type="string"/>
```

And if when is not specified then you have to run the calculation whenever anything changes, ie is what you basically have to do already. Just thought I'd throw it out there...

[And then maybe we can get rid of preload someday, and just replace it with regular XPath functions. :-)]

**Comment by mdudzinski** [comment]
@lognaturel @MartijnR Events are fired before calculations. It's what I see in the code. This is also stated in the commcare docs (Cascade section):

> Actions always fire before any bind logic is evaluated. So an xforms-ready event fires before relevants, calculates are evaluated.

It seems like this idea will not work because `/data/ready` will be populated before calculations are triggered but please correct me if I'm missing something in this idea.

On the other hand, introducing a new event - as @lognaturel suggested - may work. Either `xforms-value-changed` or something like `xforms-ready-post-calculations` to support your idea. 

Also, finalizaing a form shouldn't trigger recalculation if commiting an answer will be fixed as shown [here](https://github.com/mdudzinski/javarosa/commit/8ae88bdbc866265b03e2b1b12d35e562bc188ac1).

@tiritea `<setvalue>` mechanism is already implemented in JavaRosa so no extra work to be done here but I see your point. I think the idea of using the `when` attribiute is really interesting but may be far more technically challenging than supporting a new xform event. I think there are also big concerns about straying further from the W3C XForms evaluation rules and XForms specification in general.

**Comment by mdudzinski** [comment]
@MartijnR @lognaturel I tested the idea with `/data/ready` and `xforms-ready-post-calculations` event and the following calculation and setvalue: 
```
...
<bind calculate="if(/data/ready = 'true', now(/data/Number), null)" nodeset="/data/Timestamp" type="dateTime"/>
<setvalue ref="/data/ready" event="xforms-ready-post-calculation">true</setvalue>
...
``` 
Unfortunately this doesn't work because `setvalue` triggers calculations that depend on the `/data/ready` node which causes the `now()` function to run at form load anyway (at `xforms-ready-post-calculation` event)...

Any chance I missed something?

**Comment by tiritea** [comment]
Yes, for better or worse, XForms 1.1 seems to have already (attempted?) to cover this area, [here](https://www.w3.org/TR/xforms/#action).

I guess if *I* personally - as an XForms implementor - wanted to run certain calculations only at certain times [aside, including `preload` for that matter!], I would have probably tried re-using as much of what was already present (ie `calculate="...",` XPath extension functions, etc) which I've already had to implement, and simply extend the XML with an appropriate new attribute (aka `when`) to optionally indicate when to run a `calculate`.

Unfortunately, I wasn't around when the W3C working group came up with all this, so I dont know the rationale behind their (far) more complex approach. But then, as an ex-standards guy myself, I know what happens when you put a bunch of opinionated, pedantic, standards people in the same room... :-)

**Comment by mdudzinski** [comment]
@lognaturel I have a new idea which requires only `xforms-value-changed` event implementation.

Below go the details. It may not be the best place to describe so I can move it to collect/javarosa issues if needed.

It only needs `xforms-value-changed` event implementation on the JavaRosa side which is just a few lines of code (+ tests). Rest of the logic is handled on the client side by a custom implementation of `org.javarosa.core.model.Action` class. The new action is registered for the `xforms-value-changed` event. When a value of a node is updated, this action takes the name of the node and looks for a timestamp node at the same level (under the same parent) and sets the value. Timestamp node names will have to follow a certain convention so they can be found and updated. For example, if updated node is `/data/somegroup/somequestion` then its timestamp is `/data/somegroup/somequestion__timestamp`. 
It's just an example convention, the actual implementation may be different. For example hold timestamps at different group at root level, in another instance or even create timestamp nodes on the fly (instead of looking for existing ones).

I've got working - but dirty - code with this approach:
* https://github.com/mdudzinski/collect/commit/fb2406e4e451bf66d64afb53b9fc70a69d9674cc
* https://github.com/mdudzinski/javarosa/commit/9ca2e47b690a477c639fd9af560bcbbc0ddfdd42
which can be used with this form: 
[capturing-timestamps.xml.txt](https://github.com/opendatakit/xforms-spec/files/1501320/capturing-timestamps.xml.txt)
(note that the dirty implementation uses `__Timestamp` so a slightly different postfix than in the example above)

The biggest advantage is that it may not require any changes in XSLForm but I guess this will depend on the actual implementation. I'm not sure if it's possible to create "questions" without their representation in the body so they are hidden but present in the instance.

**Comment by mdudzinski** [comment]
@tiritea I agree and I think this is something - greater control over triggerables - ODK may need in the future. It's a bit different by nature from other XForm implementation so it might make more sense to add custom extensions to the specs but I guess this would need a discussion in a separate thread :)

**Comment by tiritea** [comment]
'hidden questions', reserved node naming [which would arguably require telling KoboToolbox users "You cant end a question with '_Timestamp'"...] is sounding like a bit of a rat-hole we might not want to go down... Bear in mind, whatever we come up with we may have to support (legacy) forms exploiting it till the end-of-time-as-we-know-it :-(

Honestly, I think sullying the otherwise pretty pristine XForm instance XML with weird stuff to try an support events is probably opening a Pandora's box of potential future trouble. I dont know what will be involved on the javaRosa/ODK Collect in terms of implementation, but I would hope there could be a better way. Sorry, just my $0.02

[Utter and complete aside: @lognaturel So I *finally* figured out whence your sobriquet! Only took me 8 months (sorry, I'm a bit 'slow'... ;-) Clever, in a very geek-ish sorta way. :-)]

**Comment by mdudzinski** [comment]
@tiritea The reserved node naming would be the client side implementation. So no need for KoboToolbox or other implementations to follow this pattern. As I suggested, this may use different approach, for example custom attributes on the instance node instead certain names. But anyway, it's completely up to the client. The key idea here is to add the xform events to the ODK XForm Spec so the client apps that uses an engine implementing this spec can use those events to achieve their needs. 
I was thinking about an approach that requires minimum changes in the spec and the engine (JavaRosa in that case).

But I like your idea because it's explicit, more general and is on the engine side. May be technically challenging but should offer more in the future. 

I'm also exploring the Actions mechanism from XForms 1.1.

**Comment by tiritea** [comment]
My concern is what might happens if, per-chance, someone happened to create a regular XML instance node having a "..._Timestamp" suffix (aka inadvertently using a 'reserved word'). Would that confuse the client? Given the choice, I'd probably be more inclined to introduce a new attribute, rather than rely on a (new) custom naming scheme involving XForm properties that are presently exposed to existing tooling having nothing to do with actions [sic].

**Comment by tiritea** [comment]
> ...But I like your idea because it's explicit, more general and is on the engine side. May be technically challenging but should offer more in the future.

What I was thinking was, when the client detects said event, just kickoff a regular 're-calculate everything' operation, but this time filter it for only binding calculations whose `when` matches the event [and if anything changes, you may have to recalculate _everything_, but that's normal calculate-recalculate behavior].

**Comment by lognaturel** [comment]
> introduce a whole new mechanism of <setvalue event=...> events either (arguably, their xforms-ready is doing what jr:preload is supposed to be there for...)

I think the `setvalue`, etc way is the W3C XForms way, no? I believe what Dimagi did was deprecate `jr:preload` in favor of the more W3C XForms-ish mechanism. I would be in favor of doing something like that but it's probably a separate conversation.

### The`__timestamp` proposal
> My concern is what might happens if, per-chance, someone happened to create a regular XML instance node having a "..._Timestamp" suffix (aka inadvertently using a 'reserved word'). Would that confuse the client?

If I'm understanding @mdudzinski's proposal correctly, I believe the person authoring a form would **need** to explicitly add the node following the naming convention to "give a place for the value to go." Going with something like `__timestamp` with a double underscore would make it really unlikely to be an accident. The value of that node would be set if the value of the node with the prefix name changed. For example, I'd add `my_text` and `my_text__timestamp`.  `my_text__timestamp` would not have a corresponding `body` element and would automagically be populated if/when `my_text` changed. If I did add `my_text__timestamp` and expect that to be used for something else (e.g. a calculate), I suppose evaluation order rules would determine what value would "win". 

I don't love the magic but it'd be really easy for users to understand and use. It has a certain elegant simplicity to it.

### The XForms way
Am I understanding correctly that the "W3C XForms way" to get a timestamp representing the last time a node called `my_text` was edited would be to add a `setvalue` block within the `my_text` `input` block giving something like:
```xml
<bind nodeset="/data/my_text" type="string" />
<bind nodeset="/data/my_text_timestamp" type="dateTime" id="text_timestamp_id" />
...
<input ref="/data/my_text">
    <setvalue event="xforms-value-changed" bind="text_timestamp_id" value="now()" />
</input>
```

The `id` attribute on `bind` is in W3C XForms as an optional identifier to uniquely identify a node as described [here](https://www.w3.org/TR/xforms11/#structure-bind-element) but it is not in ODK XForms as far as I know. I can't tell if replacing `bind="text_timestamp_id"` with `ref="/data/my_text_timestamp"` would be W3C XForms valid in this context.

`xforms-value-changed` is better described [here](https://www.w3.org/TR/xforms/#evt-valueChanged) with examples.

The great thing with this approach is that everything is explicit in the form. That means the node that will hold the timestamp can have an arbitrary name and that there's less magic. But it requires the introduction of a number of concepts which may or may not be useful otherwise.

### The `when` proposal
The `when` concept also makes things explicit which is great. It doesn't correspond to anything XForms-ish, though. And it seems like the implementation needs may be similar to the more pure XForms approach.

@tiritea What would a `when` expression look like for an event like `xforms-value-changed` that require a corresponding way to identify which node we want to pay attention to? Presumably another attribute for something like
```xml
<bind nodeset="/data/my_text_timestamp" calculate="now()" when="xforms-value-changed" which="/data/my_text" type="dateTime"/>
```
or maybe 
```xml
<bind nodeset="/data/my_text_timestamp" calculate="now()" when="xforms-value-changed(/data/my_text)" type="dateTime"/>
```

### Misc.
> [Utter and complete aside: @lognaturel So I finally figured out whence your sobriquet! Only took me 8 months (sorry, I'm a bit 'slow'... ;-) Clever, in a very geek-ish sorta way. :-)]

@tiritea People sometimes have that "ooohhhhhh," moment after YEARS of knowing me! In the sixth grade my friend Mickaël pointed out that my name could be explained to anglos as LN, a few years later I learned logarithms in French and got on IRC... and now I'm stuck with the handle forever! So yes, I'm intimately familiar with the concept of snap decisions that stick around forever... 😁

**Comment by lognaturel** [comment]
I'll add that I think the reason the events/actions mechanism was introduced in W3C XForms is that it potentially allows much more than firing calculates at specific times. 

For example, a `saveIncomplete` `bind` attribute was added to Collect/ODK XForms at some point to force an instance save after specific nodes have been "visited." The approach is to count on the fact that the question will be rendered when it is accessed which of course doesn't make sense in a `field-list` or single-page context. This is the same kind of "hack" that people were previously relying on for lightweight timestamping. This would better be implemented with some kind of `save-draft` action also triggered on a `xforms-value-changed`, I think.

**Comment by MartijnR** [comment]
Thanks for the overview @lognaturel  and nice find about how `setvalue` could work. I had no idea it could be placed in the body underneath a form control!

I think your example could indeed also be changed to:

```xml
<bind nodeset="/data/my_text" type="string" />
<bind nodeset="/data/my_text_timestamp" type="dateTime" />
...
<input ref="/data/my_text">
    <setvalue event="xforms-value-changed" ref="/data/my_text_timestamp" value="now()" />
</input>
```

I found a reference [here](https://www.ibm.com/support/knowledgecenter/en/SSS28S_8.1.0/XFDL/i_xfdl_g_xforms_events_xforms-value-changed.html) (the last example on that page).

So that leaves few new concepts to add. Just `setvalue` with the `xforms-value-changed` event. And then later we can replace preload items adding just new events if we want.

I'll think about the 3 proposals a bit more.

**Comment by tiritea** [comment]
@lognaturel asked:

> What would a when expression look like for an event like xforms-value-changed that require a corresponding way to identify which node we want to pay attention to?

To be honest, I'm not entirely sure why `xforms-value-changed` is needed in the first place - whenever **anything** changes in the instance XML, the client pretty much **must** rerun any and all binding calculations, since the calculations may contain XPath expressions referencing said changed element. Unless the client is particularly smart and has introspected all the XPath expressions to build up a complete dependency tree (when first parsing the XForm?), which I'm pretty sure javaRosa doesn't. Rather, javaRosa flags if any of these re-calculations in turn change something *else*, and if so re-runs the calculations again. And again... until it finally gives up [which I think it does after about 3 iterations; just run a form with A=B+1 and B=A+1 and wait for the smoke to rise... ;-)]

Which is to say, *for the purpose of re-running a calculation if `xform-value-changed`*, it is redundant (but it suppose it could still be useful to trigger other non-recalculation based consequences...)

**Comment by lognaturel** [comment]
I think what we want to do is **ONLY** run something in the event that a specific node has changed, right? I believe that's what `<setvalue event="xforms-value-changed" ref="/data/my_text_timestamp" value="now()" />` means.

**Comment by tiritea** [comment]
Ah. I see what you mean. Hmm...

**Comment by mdudzinski** [comment]
@MartijnR @lognaturel 
If the `<setevent>` is placed in the body, then the timestamp input will be visible to a user, won't it? I thought it's expected for timestamps to be hidden. Perhaps both ways should be allowed?

It seems like the `id` attribute on `bind` is in the JavaRosa code but it is not present in the spec.

**Comment by lognaturel** [comment]
My understanding is that the action (in this case `setvalue`) will always be nested in the `bind`. I think it's whether or not the node that will "receive" the value is in the body that determines whether it's shown to the user. That's `/data/my_text_timestamp` in my example above. As long as that's not in the body I believe it will be "hidden."

**Comment by MartijnR** [comment]
That is also my understanding. The input and setvalue have separate bind refs, and only the input will show in the UI.

A little deviation, but I wanted to brag by commenting on:
>Unless the client is particularly smart and has introspected all the XPath expressions to build up a complete dependency tree (when first parsing the XForm?), which I'm pretty sure javaRosa doesn't.

Enketo definitely does something like this. This is how Enketo is able to keep a gigantic form always completely up-to-date (logic-wise) regardless of whether it's divided into pages or not. 

You're definitely right that this is hard and cannot be perfect (it isn't in Enketo) so there is always a risk that evaluations run when they shouldn't (or don't need to). So something with a node-specific change event seems like the way to go for this feature.

**Comment by mdudzinski** [comment]
@MartijnR @lognaturel Oh that's right, `<setvalue>` and the `<input>` have different refs, I missed that! 

Now it makes sense and looks like a feasible approach. Being "XForms-ish" is also an advantage 😃 

I believe JavaRosa does something like this as well. There is a code for "cascading" calculations that are depended on each other. E.g. `/data/nodeC` calculations depends on `/data/nodeB` value which depends on `/data/nodeA` value. Not sure if it's bug free though hmm

**Comment by lognaturel** [comment]
Looks like we're getting somewhere! I'm imagining @tiritea still lost in thought after his last "Hmm..."... 😉

**Comment by tiritea** [comment]
> Enketo definitely does something like this. This is how Enketo is able to keep a gigantic form always completely up-to-date (logic-wise) regardless of whether it's divided into pages or not.

Impressive! I try to avoid having to introspect or otherwise parse out anything in XPath expressions (mostly b/c its a royal PITA). But it'll be the only way to optimize my re/calculations, someday... sigh.

> Being "XForms-ish" is also an advantage

Alas, yes. [and since I've been beating up @lognaturel , @yanokwa , et al for months now about violating existing standards, I'd be a bit of a hypocrite to now suggest otherwise! 😄 ]

**Comment by lognaturel** [comment]
> and since I've been beating up @lognaturel , @yanokwa , et al for months now about violating existing standards, I'd be a bit of a hypocrite to now suggest otherwise! 😄

Hopefully we are now in a new era of more careful consideration of existing standards and how additions may fit in! But none of this is easy so we have to be ever vigilant not to let misunderstandings or errors slip in.

Are we all on board? @MartijnR?

**Comment by MartijnR** [comment]
Yes! Whoever wants to write it up just let us know in this thread. (I may do it if nobody beats me to it in the next week(s).)

In the future let's get rid of pre-loaders using the same feature, once we're up for it. One less unnecessary feature.

**Comment by lognaturel** [comment]
💫 Thanks all!

I'll take a first stab at documenting events and actions now. I'll surely need some help to be as clear and complete as possible.

**Comment by tiritea** [comment]
> In the future let's get rid of pre-loaders using the same feature, once we're up for it. One less unnecessary feature.

You got my vote! The only rightful place for pre-loaders is before going out drinking... :smile: 

This `setvalue/action` stuff is certainly going to be a bit of work for me, but at least it is a far more consistent, general purpose mechanism, which can serve many useful purposes; so the effort will pay off. And nobody is going to get beat up over it. :wink:

**Comment by lognaturel** [comment]
> The only rightful place for pre-loaders is before going out drinking... 😄

Hehe.

> And nobody is going to get beat up over it. 😉

Another day with shins intact!! 🎉 

Please see what you think of #155.

**Comment by lognaturel** [comment]
Oh, and I'm a "yes please" for

> In the future let's get rid of pre-loaders using the same feature, once we're up for it. One less unnecessary feature.

**Comment by MartijnR** [comment]
This was closed by https://github.com/opendatakit/xforms-spec/pull/155
