### ISSUE TITLE
Identify functions that come from XForms 1.0

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#139]
For example, https://opendatakit.github.io/xforms-spec/#fn:count-non-empty is identified.

**Comment by MartijnR** [comment]
And, if found, replace the XPath reference, perhaps? 

E.g. https://www.w3.org/TR/2003/REC-xforms-20031014/slice7.html#fn-min

instead of the (current): https://www.w3.org/TR/xpath-functions/#func-min

The advantage is that the XForms 1.0 spec is much easier to read.

The disadvantages are that maybe XPath is more thorough and that new implementers likely pick an XPath library instead of an XForms library.

I think the advantage outweighs the disadvantages (and in any case an XPath library will require customizations to become ODK spec compliant).

**Comment by MartijnR** [comment]
As part of this:

* [x] if() function is actually an XForms 1.0 function: https://www.w3.org/TR/2003/REC-xforms-20031014/slice7.html#fn-if, which I had failed to find.
* [x] instance() : https://www.w3.org/TR/2003/REC-xforms-20031014/slice7.html#fn-instance
* [x] bind attributes 
* [x] main elements: bind, repeat, group, instance
* [x] current() and random (XForms 1.1)
* [x] do XForms 1.1 after all? https://github.com/opendatakit/xforms-spec/issues/60

**Comment by lognaturel** [comment]
Ah, yes, I'm pro using the XForms reference as well.

**Comment by MartijnR** [comment]
Sorry @opendatakit-bot, I'm still working on it.
