### ISSUE TITLE
add documentation for current() under XPath Path ?

### ISSUE THREAD

**Issue by yanokwa** [getodk/xforms-spec#15]
This should reference the '.' of the primary instance (at the moment, there is one known variance http://code.google.com/p/opendatakit/issues/detail?id=1070&start=300 ).

It is useful when you need to refer to '.' in the primary instance from within a filter condition being applied to a secondary instance.

**Comment by MartijnR** [comment]
It's now under the XPath Expressions (but flagged it with review because I think the description is not correct - I don't completely understand this function yet). 

It put it there as it seemed to be an XPath function that returns a node, like indexed-repeat() and instance(). 

Shall we just add a reference to these functions in the XPath Path section?

**Comment by yanokwa** [comment]
@mitchellsundt What do you think?

**Comment by mitchellsundt** [comment]
Add this -- otherwise, looks good:

Unlike instance(...), which always requires an absolute path, current() can
be used with relative references.

   current()/.  -- refers to the '.' node in the primary instance
   current()/..  -- refers to the '..' node in the primary instance

On Thu, Oct 2, 2014 at 2:50 PM, Yaw Anokwa notifications@github.com wrote:

> @mitchellsundt https://github.com/mitchellsundt What do you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/opendatakit/odk-xform-spec/issues/15#issuecomment-57715571
> .

## 

Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com
