### ISSUE TITLE
Can form submission method be changed to post rather than form-data-post

### ISSUE THREAD

**Issue by lognaturel** [getodk/xforms-spec#151]
From @MartijnR on #149:
> I think method should be in there (but it should actually have value "post" in hindsight). Your question leads me to suspect that ODK Collect is not actually reading/using this attribute. In that case, we could change it to "post" perhaps....

Aggregate expects `form-data-post` but it does seem very odd. I don't know whether there's a reason for it and would be worth more digging. `post` would certainly make more sense. 

- [x] Figure out whether `post` works with current Aggregate (does not)
- [ ] See if there are any breadcrumbs suggesting why `form-data-post` was used

**Comment by MartijnR** [comment]
@lognaturel could Aggregate support both `post` and `form-data-post`, and we document `post` only?

**Comment by lognaturel** [comment]
`post` doesn't currently work with Aggregate but I don't see any issue with also supporting `post`. Still no idea why `form-data-post` was used.

@yanokwa, @ggalmazor, do you see anything I may be missing?

**Comment by yanokwa** [comment]
I have no idea. @wbrunette? Maybe a GAE thing?

**Comment by lognaturel** [comment]
As far as I can tell, `form-data-post` only exists in the ODK world. The type specified in the MIME envelope of submissions is `multipart/form-data` so maybe the idea was to have different `method` "`post` variants" for different kinds of submission formats? I can't think of what those would be and using `post` still seems like the right approach.

**Comment by lognaturel** [comment]
This would also require some coordination with other members of the ecosystem. For example, Ona probably expects `form-data-post`. @ukanga?

**Comment by wbrunette** [comment]
From memory (haven't dug into the code), I thought we were using POST with "multipart/form-data".  This was chosen so you could upload binaries and such without worrying about bad characters and such. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST
https://stackoverflow.com/questions/4526273/what-does-enctype-multipart-form-data-mean
https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4

Since ODK is designed to transmit multiple files in one POST, the multipart/form-data seemed like the best choice. As this enables the submission and pictures/audio/video/etc files to be uploaded in one POST.  

Again going off memory, if you give me pointers to lines of code in repos I am happy to look into the details. I am wondering if "form-data-post" is the same as POST with "multipart/form-data" in whatever library is being used.

**Comment by lognaturel** [comment]
That's exactly right, @wbrunette. The OpenRosa standards specify that a submission is sent as a `multipart/form-data POST`.

I don't see any evidence that `form-data-post` exists outside of the ODK world. 

I believe the only usage of `form-data-post` in the ODK world is to check that it is the specified method: https://github.com/opendatakit/aggregate/blob/2786f4a52165a93a14768c4ba7a4e97ea6bcf7c6/src/main/java/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java#L550

I like this passage on why it's best not to define custom HTTP methods: https://www.safaribooksonline.com/library/view/restful-web-services/9780596809140/ch01s12.html

**Comment by MartijnR** [comment]
I am!

**Comment by lognaturel** [comment]
Closed by #185.
