### ISSUE TITLE
count-selected() has been misdocumented?

### ISSUE THREAD

**Issue by yanokwa** [getodk/xforms-spec#152]
According to @tiritea at  https://forum.opendatakit.org/t/-/10244/3 , `count-selected()` has been misdocumented

>It doesn't actually take a _string_, but rather a _node_.

It'd be good to confirm, and if it is a mistake, fix.

**Comment by tiritea** [comment]
by which I mean, this is strictly correct:
`relevant='count-selected(/path/to/node) > 2'`
but this is wrong (but rather implied by the current wording):
`relevant='count-selected("this|that|other") > 2'`
The value of the XML instance node will be interpreted as a string by count-selected (ie '|' delimited list of option values), but the XPath function itself doesnt seem to accept the string literal on it own.

**Comment by MartijnR** [comment]
I think you're right. It takes a node indeed. Thank you!

P.S.
The "|" must be some JavaRosa internal thing.  In your example the observation that (`count-selected("this that other") > 2` doesn't work (and deviates from spec) would be correct because the delimiter in a multi-select is a space. The "|" is to join nodesets together as in `count(//a | //b) = 2`.
