### ISSUE TITLE
Change point, geoshape and geotrace to eWKT or add eWKT as a type

### ISSUE THREAD

**Issue by khalifeserge** [getodk/xforms-spec#173]
I have found myself using ODK to collect more and more geographic data using ODK collect and I was delighted when I saw features from GeoODK migrate to ODK collect. However the way the geometries are being stored non standard and limiting incertain ways.  Below is an extract of the specs:

type | description
-- | --
geopoint | Space-separated list of valid latitude (decimal degrees), longitude (decimal degrees), altitude (decimal meters) and accuracy (decimal meters)
geotrace | Semi-colon-separated list of at least 2 geopoints, where the last geopoint’s latitude and longitude is not equal to the first
geoshape | Semi-colon-separated list of at least 3 geopoints, where the last geopoint’s latitude and longitude is equal to the first

I read a thread on [https://forum.opendatakit.org/t/geo-fields-should-be-stored-in-wkt-format-well-known-text/7048](https://forum.opendatakit.org/t/geo-fields-should-be-stored-in-wkt-format-well-known-text/7048) were the proposal to use WKT was shelved as a aggregate issue last year. However I would like to revive the issue by providing the following points:

- The ODK format does not allow multiple lines to be collected in the same field of a geotrace. A Y split in the line cannot be collected
- The ODK format does not allow to collect multiple polygons or polygons with holes
- There exist multiple java libraries that provide geoprocessing functions. The could be used in Collect to for example check if a point being collected is within a polygon (GeoFence)
- The WKT format is easily used in many of the database engines with gis capabilities

I know this is a long shot for the data type point since it is already established and has been for a while, but geotrace and geoshape are newer.  

I would recommend storing the a point in the 4D (x, y, z, m) representation where z is altitude and m is accuracy

Thank you for all the improvement made to ODK over the years, it is much appreciated.

**Comment by MartijnR** [comment]
Thanks for your suggestion. Changing the geo formats is a discussion we've had and decided not to go for (ref: your link above). Geoshapes and geotraces have been in use [since 2014](https://blog.enketo.org/geo/) as well, e.g. in Enketo. This would be a great issue to add to e.g. Aggregate though (conversion to WKT).

However, if you'd like to propose adding a fourth geo datatype for multi-geoshapes e.g., please post a message in the forum with your proposal. I'd advocate to use the current formats as a basis.

Will close this now.
