### ISSUE TITLE
Cross-platform PRNG for randomize()

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#176]
Continuing on from @ln's comment [here](https://github.com/opendatakit/xforms-spec/pull/167#issuecomment-381241737) and our spec which says about the PRNG to be used:

> linear congruential pseudorandom number generator as the one used by the next() function in Java v7

After further investigation, it seems to me that is not possible to implement Java's PRNG in JavaScript and have a guaranteed equal result. I think this may be related to datatypes (the total space for `long` in java is not available as `number` in javascript) but am not sure. This would be a problem for the scenario where a record is created in e.g. ODK Collect and then edited in Enketo or vice versa, or where data is collected with multiple clients for the same scientific survey.

I'd like to propose to clearly define a simpler PRNG that can be implemented in any language. E.g. something like this: https://gist.github.com/blixt/f17b47c62508be59987b (Park Miller PRNG), but any cross-platform algorithm would work.

I've implemented this here: https://github.com/enketo/enketo-xpathjs/blob/feature/randomize/src/shuffle.js

It changes the test results as follows for array [A,B,C,D,E,F]:

| seed | result |
|------|-------|
| 42 | BDFECA |
| -42 | EDACBF |
| 1 | ECBDFA |
| 11111111 | ADBCEF |

If possible to hold off on publishing a new Collect version with `randomize()`, that would be great.

**Comment by lognaturel** [comment]
Interesting! Using Park Miller PRNG seems fine to me. @yanokwa @ggalmazor any objections?

**Comment by yanokwa** [comment]
I'm fine with Park Miller. Anything to make @MartijnR's life easier :)

**Comment by ggalmazor** [comment]
Hi @MartijnR, @lognaturel, @yanokwa!

~I'm sure I'm missing something, but I've found several implementations of Fisher-Yates and LCGs. [This search](https://www.npmjs.com/search?q=fisher-yates) will show modules that do a Fisher-Yates shuffle and most of them allow passing a [linear congruential generator](https://www.npmjs.com/search?q=lcg). I think this combination of modules could do the trick:~
- ~https://www.npmjs.com/package/fisher-yates~
- ~https://www.npmjs.com/package/compute-lcg~

    ~Both have good reported quality and maintenance stats.~

~I would advise resisting as long as possible to implement this kind of algorithms in our code base and always rely on third party, battle-tested libraries when needed.~

After doing some research now I understand the problem is in the LCG, not in the Fisher-Yates algorithm.

I've created a small toolbench to work out differences between outputs using different algorithms. Maybe this will help us compare the Java and JavaScript implementations and verify they produce the same output. https://github.com/ggalmazor/ShuffleBench

**Comment by ggalmazor** [comment]
Update: I've worked out a working cross-platform version of the FisherYates + ParkMiller shuffling algorithms. Check it out here: https://github.com/ggalmazor/ShuffleBench

The good news is that, at least on the JS side, standard node modules can be used (no need to implement anything). These are the ones I've verified that I can produce the same output in Java:

- https://www.npmjs.com/package/fisher-yates
- https://www.npmjs.com/package/park-miller

On the Java side it trickier because of the way JavaScript handles numbers (IEEE754 64bit double floating point numbers). This forces us to use floating point arithmetics and to implement our own version of Fisher-Yates using the double number generator as opposed to the native `Collections.shuffle` method, which used the int number generator. These apparently small differences have a great impact while choosing target indexes for the value swaps in Fisher-Yates.

**Comment by ggalmazor** [comment]
Just saw a [nice tweet about our problem here](https://twitter.com/b0rk/status/986424989648936960):
![image](https://user-images.githubusercontent.com/205913/38933770-3a9485b4-431a-11e8-9fce-23dee5cf1621.png)

**Comment by lognaturel** [comment]
Really nice toolbench and very appropriate comic, @ggalmazor! Given that we have matching Java and Javascript implementations, I think it's safe to go with something like "pseudorandom numbers are generated with the Park Miller algorithm using 64 bit floats." The two NPM packages can act as reference implementations. @MartijnR does that work for you?

**Comment by MartijnR** [comment]
Thanks a lot! I will check this out before Monday. I think we may need to specify the exact values of the constants used in the Park Miller pseudo random number generator (unless those are fixed in all implementations).

**Comment by lognaturel** [comment]
> I think we may need to specify the exact values of the constants

I believe 16807 and max int 32 - 1 are part of the algorithm - https://pdfs.semanticscholar.org/9af1/2693368d7c76ea5b0ee4bf7e729de0b6f089.pdf

**Comment by MartijnR** [comment]
This works well! The only difference with what I had implemented is that I used a Fisher Yates _in-place_ shuffle (equivalent to changing `const shuffle = require('fisher-yates/inplace')`. In-place is slightly more efficient, but only about 10% or so with the lemario.txt file in JavaScript (not sure about Java). So we can update the spec to make clear this is not an in-place shuffle. Thanks!

Nice toolbench @ggalmazor!

Out-of-place shuffle test results:

| seed | result |
|------|-------|
| 42 | AFCBDE |
| -42 | EDAFBC |
| 1 | BFEACD |
| 11111111 | ACDBFE |

**Comment by ggalmazor** [comment]
Thanks, @MartijnR! I'll update https://github.com/opendatakit/javarosa/pull/296 to add a note with what you've said. I'll also add a unit test with the same table of results.
