### ISSUE TITLE
Earth radius in area() and distance()

### ISSUE THREAD

**Issue by MartijnR** [getodk/xforms-spec#181]
We've used the Earth's radius at the equator (the _nominal equatorial Earth radius_) so far and documented this.

@dcbriccetti is proposing to use the **mean** earth radius instead.

So 6,371,000 meters instead of the currently used 6,378,100 (_nominal equatorial Earth radius_) meters.

It makes sense to me. What do you all think?

The disadvantage is that we're changing values that were calculated previously. E.g. if an old record is opened for editing, the calculated area() will change.

**Comment by dcbriccetti** [comment]
To be precise, we’ve been using a strange, hectometer-rounded value of 6,378,100 meters instead of the 6,378,137 meter value that NASA gives us here:
https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html.
My suspicion is that that value was chosen to jibe with the results from 
https://www.mapdevelopers.com/area_finder.php?polygons=%5B%5B%5B%5B38.25284520406%2C21.763313487427013%5D%2C%5B38.253030558372%2C21.75586767520099%5D%2C%5B38.250722020942%2C21.755803302184972%5D%2C%5B38.250620915437%2C21.762948707000987%5D%2C%5B38.251834172216%2C21.756929829971%5D%2C%5B38.25284520406%2C21.763313487427013%5D%5D%2C%22%230000FF%22%2C%22%23FF0000%22%2C0.4%5D%5D ,
which was used to produce test data for the area calculation.

**Comment by lognaturel** [comment]
In defense of the originators of the code, 6,378,100m is a common approximation including on Wikipedia: https://en.wikipedia.org/wiki/Earth_radius!

Switching to the mean radius seems fine to me. I don't think there would be much negative impact on users but we can make sure to announce the change in advance through betas and such. I suspect most people doing deep analysis on traces and shapes are doing so on the backend as @MartijnR mentioned somewhere.

**Comment by dcbriccetti** [comment]
Sorry. I’m having second thoughts.

The test data for area in JavaRosa is based on the 6,378,100m approximate equatorial radius, and the distance calculation code I’ve just added produces consistent results when given that same value. If we switch to the mean radius I’ll need to generate all new test data. And, as has been said, the current level of precision is adequate.

So, I’d like to withdraw my request for the change.

**Comment by lognaturel** [comment]
😄I don't feel strongly either way. I agree that what we have now is adequate and it's definitely simpler/less error prone to keep it.

**Comment by MartijnR** [comment]
Cool with me. Let's leave as is and use current radius for both functions. Thanks!
