### ISSUE TITLE
Make the status of this documentation clearer

### ISSUE THREAD

**Issue by alxndrsn** [getodk/xforms-spec#46]
From the discussion at https://github.com/opendatakit/collect/issues/266, this repo does _**not**_ contain the definitive spec for ODK Collect's XForms implementation.  The documentation does have a note at the top, reading

> Work in Progress - Pending peer-review and approval

It would be great to add a link in the same place to the definitive spec at https://bitbucket.org/javarosa/javarosa/wiki/xform

**Comment by MartijnR** [comment]
It's still far more accurate and complete than the bitbucket page though... ;) That page was used as the basis. The best spec at the moment is the [CommCare XForm Spec](https://dimagi.github.io/xform-spec/) (minus the bits that are different in CommCare), because it was fairly thoroughly reviewed by their JavaRosa developers.

I think we just need to somehow clear the outstanding issues here (the non-controversial ones), get at least one fabulous ODK developer to review it, and then remove the warning.

**Comment by alxndrsn** [comment]
@MartijnR are you volunteering?  ref https://github.com/opendatakit/collect/issues/266 :¬)

**Comment by MartijnR** [comment]
:) I would like to do it as it's unfinished business for me. I'm just trying to get my hours paid for by a client once I complete some more pressing work for them. I think it's about a 1-2 days of work.

**Comment by MartijnR** [comment]
* [ ] remove banner
* [ ] liaise with Dimagi to replace https://bitbucket.org/javarosa/javarosa/wiki/xform with empty page with 2 links to ODK and CommCare XForms specifications.

**Comment by lognaturel** [comment]
@alxndrsn Has your question been convincingly addressed? We will also be adding a little bit of historical context in the introduction with #64.

**Comment by alxndrsn** [comment]
Not entirely clear! Is https://opendatakit.github.io/xforms-spec/ now the correct reference for ODK XForms?

**Comment by lognaturel** [comment]
Yes, that's correct. There's now a link from the Collect repo README to it as well.

**Comment by alxndrsn** [comment]
Great, thanks :¬)
